In [1]:
import cv2


In [2]:
cap = cv2.VideoCapture(1)

In [80]:
ret , photo = cap.read()

In [81]:
type(photo)

numpy.ndarray

In [83]:
b ,g ,r = cv2.split(photo)

In [86]:
r.shape

(480, 640)

In [72]:
photo.shape

(480, 640, 3)

In [87]:
cv2.imshow("hi", photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [89]:
# photo[: , : ,  [0, 2]  ]  = 0
photo

array([[[133, 117,  98],
        [136, 119, 100],
        [138, 120,  99],
        ...,
        [165, 169, 176],
        [165, 168, 174],
        [164, 166, 173]],

       [[135, 117,  98],
        [135, 117,  98],
        [136, 118,  99],
        ...,
        [164, 168, 173],
        [163, 167, 171],
        [164, 167, 171]],

       [[136, 118,  99],
        [135, 117,  98],
        [135, 117,  98],
        ...,
        [162, 167, 171],
        [163, 167, 171],
        [164, 167, 171]],

       ...,

       [[ 41,  41,  41],
        [ 42,  43,  43],
        [ 44,  47,  47],
        ...,
        [ 78,  71,  59],
        [ 78,  72,  59],
        [ 77,  71,  58]],

       [[ 42,  39,  40],
        [ 43,  42,  42],
        [ 45,  45,  45],
        ...,
        [ 80,  71,  58],
        [ 79,  71,  58],
        [ 78,  70,  57]],

       [[ 40,  40,  40],
        [ 41,  41,  41],
        [ 44,  44,  44],
        ...,
        [ 80,  70,  59],
        [ 79,  70,  60],
        [ 79,  70,  60]]

In [ ]:
photo

In [98]:
nphoto = cv2.blur(photo , (15,15) )

In [100]:
cv2.imshow("hi", photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [101]:
cap.release()

In [75]:
r= photo[: , : , 2:3 ] + 50

In [77]:
photo[: , : , 2:3] = r

In [78]:
photo

array([[[136, 115, 147],
        [137, 117, 148],
        [136, 115, 147],
        ...,
        [160, 167, 221],
        [157, 167, 223],
        [157, 167, 223]],

       [[136, 116, 145],
        [137, 116, 144],
        [137, 115, 142],
        ...,
        [161, 167, 220],
        [160, 166, 220],
        [161, 167, 221]],

       [[135, 117, 146],
        [135, 116, 144],
        [134, 114, 141],
        ...,
        [160, 167, 218],
        [160, 167, 218],
        [160, 167, 218]],

       ...,

       [[ 40,  40,  90],
        [ 42,  42,  92],
        [ 44,  44,  94],
        ...,
        [ 76,  68, 109],
        [ 75,  68, 109],
        [ 74,  67, 108]],

       [[ 37,  38,  85],
        [ 41,  41,  90],
        [ 44,  44,  94],
        ...,
        [ 73,  66, 108],
        [ 74,  67, 108],
        [ 75,  68, 109]],

       [[ 39,  38,  85],
        [ 41,  40,  89],
        [ 42,  42,  92],
        ...,
        [ 76,  67, 107],
        [ 76,  66, 108],
        [ 76,  66, 108]]

In [48]:
photo

array([[[  0, 114,   0],
        [  0, 116,   0],
        [  0, 116,   0],
        ...,
        [  0, 167,   0],
        [  0, 167,   0],
        [  0, 167,   0]],

       [[  0, 115,   0],
        [  0, 115,   0],
        [  0, 114,   0],
        ...,
        [  0, 167,   0],
        [  0, 167,   0],
        [  0, 167,   0]],

       [[  0, 116,   0],
        [  0, 116,   0],
        [  0, 115,   0],
        ...,
        [  0, 167,   0],
        [  0, 166,   0],
        [  0, 167,   0]],

       ...,

       [[  0,  41,   0],
        [  0,  43,   0],
        [  0,  44,   0],
        ...,
        [  0,  68,   0],
        [  0,  67,   0],
        [  0,  66,   0]],

       [[  0,  40,   0],
        [  0,  42,   0],
        [  0,  43,   0],
        ...,
        [  0,  66,   0],
        [  0,  67,   0],
        [  0,  65,   0]],

       [[  0,  38,   0],
        [  0,  39,   0],
        [  0,  40,   0],
        ...,
        [  0,  66,   0],
        [  0,  67,   0],
        [  0,  67,   0]]

In [3]:
import numpy

In [4]:
a = [ [ 1,2,3] , [4,5,6] , [7,8,9], [11,12,13] ] 

In [6]:
b = numpy.array(a)

In [18]:
b[: , 1] * 2

array([ 4, 10, 16, 24])

In [21]:
b *  2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [22, 24, 26]])

In [31]:
b[: , [0, 2] ,2]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [30]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])