In [1]:
db = ["vimal", "pop", "jack", "eric"]

In [2]:
type(db)

list

In [5]:
db[1:4]

['pop', 'jack', 'eric']

In [6]:
db[1:]

['pop', 'jack', 'eric']

In [7]:
db[:3]

['vimal', 'pop', 'jack']

In [9]:
db[:]

['vimal', 'pop', 'jack', 'eric']

In [17]:
db = [ 
      [ 1,"vimal",1111,"ok"]  , 
       [2,"pop",2222,"good" ], 
        [3,"jack",3333,"ok" ],
       [ 4, "eric", 4444, "good" ] 
     ]

In [18]:
len(db)

4

In [19]:
db[0]

[1, 'vimal', 1111, 'ok']

In [20]:
db

[[1, 'vimal', 1111, 'ok'],
 [2, 'pop', 2222, 'good'],
 [3, 'jack', 3333, 'ok'],
 [4, 'eric', 4444, 'good']]

In [26]:
db[1][3]

'good'

In [28]:
db

[[1, 'vimal', 1111, 'ok'],
 [2, 'pop', 2222, 'good'],
 [3, 'jack', 3333, 'ok'],
 [4, 'eric', 4444, 'good']]

In [24]:
db[1:4]

[[2, 'pop', 2222, 'good'], [3, 'jack', 3333, 'ok'], [4, 'eric', 4444, 'good']]

In [27]:
import numpy

In [29]:
a = numpy.array(db)

In [30]:
type(a)

numpy.ndarray

In [32]:
a.shape

(4, 4)

In [38]:
a[: , 1]

array(['vimal', 'pop', 'jack', 'eric'], dtype='<U11')

In [40]:
a[: , 1:3]

array([['vimal', '1111'],
       ['pop', '2222'],
       ['jack', '3333'],
       ['eric', '4444']], dtype='<U11')

In [43]:
a[1:3 , 1:3 ]

array([['pop', '2222'],
       ['jack', '3333']], dtype='<U11')

In [46]:
# pip install opencv-python
import cv2

In [47]:
photo = cv2.imread('vimal jim redhat.jpg')

In [48]:
type(photo)

numpy.ndarray

In [50]:
photo.shape

(2316, 3088, 3)

In [58]:
# crop image
b = photo[100:1200 , 300:2000 ]

In [59]:
cv2.imwrite("my.jpg" , b)

True

In [60]:
cap = cv2.VideoCapture(0)

In [61]:
# click photo
myphoto = cap.read()

In [62]:
len(myphoto)

2

In [65]:
ret = myphoto[0]

In [66]:
ret

True

In [67]:
aphoto = myphoto[1]

In [69]:
aphoto.shape

(480, 640, 3)

In [70]:
cv2.imwrite("vimal.png" , aphoto)

True

In [71]:
a1 = numpy.array([ [1,2], [3,4], [5,6]])

In [72]:
a1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [73]:
a1.shape

(3, 2)

In [74]:
b1 = numpy.array([ [3,3], [4,4], [5,5]])

In [75]:
b1

array([[3, 3],
       [4, 4],
       [5, 5]])

In [76]:
b1.shape

(3, 2)

In [77]:
a1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
b1

array([[3, 3],
       [4, 4],
       [5, 5]])

In [81]:
c1 = numpy.vstack( (a1, b1)  )

In [82]:
c1.shape

(6, 2)

In [84]:
d1 = numpy.hstack( (a1 , b1))

In [85]:
d1.shape

(3, 4)

In [86]:
d1

array([[1, 2, 3, 3],
       [3, 4, 4, 4],
       [5, 6, 5, 5]])

In [88]:
a1.shape

(3, 2)

In [91]:
a1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [92]:
e1 = numpy.array([1,2,3,4,5,6])

In [96]:
e1.shape

(6,)

In [97]:
e1

array([1, 2, 3, 4, 5, 6])

In [99]:
f1 = e1.reshape(-1 , 1)

In [100]:
f1.shape

(6, 1)