In [1]:
import pandas

In [3]:
dataset = pandas.read_csv('marks.csv')

In [4]:
dataset

hrs  marks
0    3     30
1    7     70
2    2     20
3    8     80

In [7]:
# y : outcome: target : DV
y = dataset['marks']

In [98]:
# x : IV :  predictor
x = dataset['hrs']

In [99]:
x

0    3
1    7
2    2
3    8
Name: hrs, dtype: int64

In [72]:
type(x)

pandas.core.series.Series

In [74]:
x1 = x.values

In [75]:
x1

array([3, 7, 2, 8], dtype=int64)

In [76]:
type(x1)

numpy.ndarray

In [21]:
x = x.values.reshape(-1, 1)

In [22]:
x

array([[3],
       [7],
       [2],
       [8]], dtype=int64)

In [12]:
from sklearn.linear_model  import LinearRegression

In [28]:
# model :  y = wx
model = LinearRegression()

In [29]:
# exp : conclude : learn find final func : model :  y = wx
# machine learning:  weight/ coeffient (w) : y = 10 x
model.fit(x ,  y)

LinearRegression()

In [30]:
# model : math function
model

LinearRegression()

In [35]:
model.coef_

array([10.])

In [101]:
# that is not avaiable : forecast / predict
model.predict([[ 9 ]] )

array([90.])

In [41]:
db = [ [1, "vimal", "ok"] , [2, "pop", "good"] , [3 , "tom", "good"]  ]

In [43]:
db[0]

[1, 'vimal', 'ok']

In [67]:
db[0][1]

'vimal'

In [68]:
type(db)

list

In [38]:
import numpy

In [45]:
# 2D : matrix
a = numpy.array([ [1, "vimal", "ok"] , [2, "pop", "good"] , [3 , "tom", "good"]  ])

In [46]:
a

array([['1', 'vimal', 'ok'],
       ['2', 'pop', 'good'],
       ['3', 'tom', 'good']], dtype='<U11')

In [48]:
a[2][1]

'tom'

In [49]:
# 1D : vector
b = numpy.array(["a", "b", "c", "d"])

In [54]:

b

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [58]:
b[1:3]

array(['b', 'c'], dtype='<U1')

In [61]:
b[:3]

array(['a', 'b', 'c'], dtype='<U1')

In [62]:
b[:]

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [91]:
b

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [94]:
d = b.reshape(-1, 1)

In [96]:
d.shape

(4, 1)

In [97]:
d

array([['a'],
       ['b'],
       ['c'],
       ['d']], dtype='<U1')

In [92]:
b.shape

(4,)

In [81]:
b

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [83]:
c = b.reshape(2,2)

In [84]:
c

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [52]:
a[1]

array(['2', 'pop', 'good'], dtype='<U11')

In [79]:
a

array([['1', 'vimal', 'ok'],
       ['2', 'pop', 'good'],
       ['3', 'tom', 'good']], dtype='<U11')

In [80]:
a.shape

(3, 3)

In [90]:
a

array([['1', 'vimal', 'ok'],
       ['2', 'pop', 'good'],
       ['3', 'tom', 'good']], dtype='<U11')

In [64]:
a[1:3]

array([['2', 'pop', 'good'],
       ['3', 'tom', 'good']], dtype='<U11')

In [66]:
a[: ,  1]

array(['vimal', 'pop', 'tom'], dtype='<U11')

In [69]:
type(a)

numpy.ndarray